### PR TITLE
Add xdebug3 config

### PR DESCRIPTION
**Pull request by kimpepper**
See https://github.com/previousnext/pnx-project/pull/546

### CODE REVIEW

**Comment by acbramley** [comment]
I think we need to change the port too:

```
php-fpm-xdebug_1  | NOTICE: PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port) :-(
```

**Comment by acbramley** [comment]
Changing to `xdebug.client_port=9003` didn't work either.

**Comment by kimpepper** [comment]
I was able to get this working by adding debug port 9003 to PHPStorm settings.

**Comment by kimpepper** [comment]
Confirming @acbramley was able to test this successfully on php8 and 7.4.

**Pull request merged**
