### PR TITLE
Override request_terminate_timeout for dev images

### PR DESCRIPTION
**Pull request by acbramley**
This fixes Xdebug timing out when stepping through code, see https://previousnext.atlassian.net/browse/DCS-709

### CODE REVIEW

**Comment by simesy** [comment]
Excellent.

**Comment by simesy** [comment]
Since you have a conf.d directory in the container, I'm not sure why you're not using it conditionally for dev/xdebug settings.

**Comment by acbramley** [comment]
@simesy not too sure what you're getting at, but I tried adding it to 50_dev.ini instead but it didn't work for whatever reason. Feel free to test.

**Comment by simesy** [comment]
FPM uses .ini for its configuration and php-fpm.conf for pool configuration files. It does look like this is a value that can go into the ini, it doesn't work like that in this setup. I guess it depends how that value finds its way to the .conf

An example of having conf overrides directory:
https://github.com/perusio/php-fpm-example-config/blob/tcp/fpm/php5-fpm.conf#L70-L72

Having the ability to override values from /etc/php/conf.d would give a lot more flexibility to developers to set up local overrides.

**Pull request merged**
